name: Generate TWRP device tree

on:
  workflow_dispatch:
    inputs:
      PY:
        description: 'Python 3 version (3.6/3.9 recommended)）'
        required: true
        default: '3.9'
      IMG:
        description: 'IMG link'
        required: true
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Prepare the environment
        run: |
          sudo apt update
          sudo apt -y install cpio wget

      - name: Prepare Python3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ github.event.inputs.PY }}
          cache: 'pip'
          
      - name: Prepare twrpdtgen
        run: pip3 install -r requirements.txt
        
      - name: download img
        run: wget ${{ github.event.inputs.IMG }}
        
      - name: run
        run: |
          mkdir out
          python3 -m twrpdtgen -o ./out/ *.img
          
      - name: Compress the package
        run: |
          cd ./out
          zip -r -9 DeviceTree.zip ./*
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./out/DeviceTree.zip
          name: TWRP_Device_Tree-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: DeviceTree 4 TWRP
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
